[package]
name = "intspector"
version = "0.1.0"
authors = ["Darren Mulholland <dmulholl@tcd.ie>"]
edition = "2018"
license= "MIT"
repository = "https://github.com/dmulholl/intspector"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
term_size = "0.3"
